import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
startup_mode = "Fullscreen"

[font]
# normal = { family = "Monofur Nerd Font" }
# size = 17
normal = { family = "GeistMono Nerd Font" }
size = 14
