[manager]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
show_symlink = true

[preview]
tab_size = 4

[opener]
edit = [
    { run = 'nvim "$@"', block = true },
]

[which]
sort_by = "desc"
