palette = 'gruvbox_dark'

format = """
($status\n)\
[](color_bg)\
$os\
$username\
[ ](bg:color_blue fg:color_bg)\
${custom.is_folder_config}\
$directory\
[ ](fg:color_blue bg:color_red)\
$git_branch\
$git_status\
$git_commit\
[ ](fg:color_red bg:color_yellow)\
$c\
${custom.cpp-gcc}\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$lua\
$python\
$cmake\
[ ](fg:color_yellow bg:color_aqua)\
$docker_context\
\
$meson\
${env_var.shell}\
$shell\
${custom.nvim}\
[ ](fg:color_aqua bg:color_bg)\
$cmd_duration\
[ ](fg:color_bg)\
$line_break$character"""

add_newline = true

[os]
disabled = true
style = "bg:color_bg fg:color_fg"

[cmd_duration]
min_time = 1_000
show_notifications = false
min_time_to_notify = 10_000

show_milliseconds = true
format = '[$duration ]($style)'
style = 'fg:color_fg bg:color_bg'



[custom.is_folder_config]
disabled = true
when = "echo $PWD | grep -q '/.config'"
symbol = ' '
format = '[$symbol]($style)'
style = 'fg:color_fg bg:color_blue'

[env_var.shell]
disabled = true
symbol = ''
variable = 'SHELL'
format = '[($symbol $env_value )]($style)'
style = 'fg:color_fg bg:color_aqua'

[shell]
disabled = true

[custom.nvim]
disabled = true
when = "echo $PWD | grep -q '.config/nvim'"
symbol = ' '
format = '[$symbol($output )]($style)'
style = 'fg:color_fg bg:color_aqua'
command = "nvim --version | head -n 1 | tr ' ' '\n' | tail -n 1"

[meson]
symbol = 'Meson: '
format = '[$symbol(\($project\) )]($style)'
style = 'fg:color_fg bg:color_aqua'



[directory]
truncate_to_repo = true
format = '[([$read_only ]($style fg:color_red_soft))$path ]($style)'
style = 'fg:color_fg bg:color_blue'
truncation_length = 5
read_only = ''

[git_branch]
# symbol = ''
symbol = '' 
format = '[$symbol $branch(:$remote_branch) ]($style)'
style = 'fg:color_fg bg:color_red'

[git_status]
disabled = true

[git_commit]
disabled = false
only_detached = false
tag_disabled = false
format = '[$tag #$hash ]($style)'
style = 'fg:color_fg bg:color_red'
commit_hash_length = 4
tag_symbol = ''



[c]
symbol = 'gcc: '
format = '[$symbol($version )]($style)'
style = 'fg:color_fg bg:color_yellow'

[custom.cpp-gcc]
symbol = 'g++: '
format = '[$symbol($output )]($style)'
style = 'fg:color_bg bg:color_yellow'
detect_extensions = ['cpp', 'c++', 'hpp', 'h++']
command = "g++ --version | tr ' ' '\n' | head -n 3 | tail -n 1"

[docker_context]
symbol = ' '
format = '[$symbol$context ]($style)'
style = 'fg:color_bg bg:color_yellow'

[golang]
symbol = ' '
format = '[$symbol($version )]($style)'
style = 'fg:color_bg bg:color_yellow'

[lua]
symbol = ' '
format = '[$symbol($version )]($style)'
style = 'fg:color_bg bg:color_yellow'

[nodejs]
symbol = ' '
style = 'fg:color_bg bg:color_yellow'

[python]
symbol = ' '
format =  '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'fg:color_bg bg:color_yellow'

[rust]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_bg bg:color_yellow'

[cmake]
format = '[$symbol($version )]($style)'
style = 'fg:color_bg bg:color_yellow'






[line_break]
disabled = false

[status]
disabled = false
style = 'fg:color_fg bg:color_bg'
format = """
[\
(Exit code: [$maybe_int]($style fg:color_red_soft))\
(Exit status: [$common_meaning]($style fg:color_orange_soft))\
(Signal: [$signal_name]($style fg:color_yellow_soft))]\
($style)\
"""

[character]
format = ' '
disabled = false

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[palettes.gruvbox_dark]
color_fg = '#ebdbb2'
# color_bg = '#32302f' # soft constrast version
color_bg = '#282828' # medium contrast version
# color_bg = '#1d2021' # hard contrast version
color_red =    '#cc241d'
color_green =  '#98971a'
color_yellow = '#d79921'
color_blue =   '#458588'
color_purple = '#b16286'
color_aqua =   '#689d6a'
color_orange = '#d65d0e'
color_red_soft =    '#fb4934'
color_green_soft =  '#b8bb26'
color_yellow_soft = '#fabd2f'
color_blue_soft =   '#83a598'
color_purple_soft = '#d3869b'
color_aqua_soft =   '#8ec07c'
color_orange_soft = '#fe8019'

[palettes.gruvbox_light]
color_fg = '#3c3836'
# color_bg = '#f2e5bc' # soft constrast version
color_bg = '#fbf1c7' # medium contrast version
# color_bg = '#f9f5d7' # hard contrast version
color_red =    '#cc241d'
color_green =  '#98971a'
color_yellow = '#d79921'
color_blue =   '#458588'
color_purple = '#b16286'
color_aqua =   '#689d6a'
color_orange = '#d65d0e'
color_red_soft =    '#9d0006'
color_green_soft =  '#79740e'
color_yellow_soft = '#b57614'
color_blue_soft =   '#076678'
color_purple_soft = '#8f3f71'
color_aqua_soft =   '#427b58'
color_orange_soft = '#af3a03'
